### PR TITLE
use bumpversion

### PR DESCRIPTION
**Pull request by minrk**
and set current to 0.5.0-dev

### CODE REVIEW

**Comment by rgbkrk** [comment]
What's the opposition to `npm version` followed by `npm publish`. The argument to  `npm version` can be major, minor, or patch - it bumps the version and tags for you.

**Comment by minrk** [comment]
@rgbkrk Not really, though I do require that tags are `X.Y.Z`, not `vX.Y.Z`. Can `npm version` be told how to format tags?

**Comment by rgbkrk** [comment]
If using [`npm dist-tag`](https://docs.npmjs.com/cli/dist-tag) directly you can, but they ominously say not to create tags beginning with v:

> Tags that can be interpreted as valid semver ranges will be rejected. For example, v1.4 cannot be used as a tag, because it is interpreted by semver as >=1.4.0 <1.5.0. See https://github.com/npm/npm/issues/6082.

> The simplest way to avoid semver problems with tags is to *use tags that do not begin with a number or the letter v*.

**Comment by minrk** [comment]
dist-tag doesn't write git tags, though, does it? `npm version` seems to unconditionally make tags with `v`. bumpversion, as is the Python way, lets you actually tell it what to do. npm, as is the Javascript way, seems to unconditionally do what I don't want it to, with no ability to tell it to do the right thing.

**Comment by rgbkrk** [comment]
Generally though, you can just override `npm version`:

```
"scripts": {
  "preversion": "npm test",
  "version": "bumpversion <args>",
  "postversion": "git push && git push --tags"
}
```

**Comment by minrk** [comment]
Ah, sure, in which case `npm version` offers nothing at all.

**Pull request merged**
