### PR TITLE
Include iojs in the test suite

### PR DESCRIPTION
**Pull request by rgbkrk**
Ensure we're working properly with iojs.

### CODE REVIEW

**Comment by minrk** [comment]
Do we need more than one iojs?

**Comment by rgbkrk** [comment]
One's a tagged version, the other is the current stable release. Up to you.

**Comment by minrk** [comment]
I care little enough about it that I think just current stable is enough.

**Comment by minrk** [comment]
Since iojs takes 10x as long as nodejs to set up on travis, I don't think we need two of them. Can you leave it as just `iojs`?

**Comment by rgbkrk** [comment]
Ew. Sure.

**Pull request merged**
