### PR TITLE
Add a Swagger Spec for the API subset required by JupyterHub

### LINKED ISSUE #39: Add a Swagger (or similar?) spec for the REST API
This would allow creation of alternative proxying setups (See https://github.com/jupyter/jupyterhub/issues/109 for a possible use case) that 'conform to the spec'.

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes #39 

Not sure exactly if this belongs here - it's only the subset that's strictly required for jupyterhub
to work properly.

### CODE REVIEW

**Comment by minrk** [comment]
If the goal is to document what JupyterHub requires and nothing else, it wouldn't belong here. But I think we should have a swagger doc here for this. If we want to keep track of the subset that JupyterHub relies upon, we can make a minimal reference on the JupyterHub repo that points to the complete spec here (e.g. JupyterHub uses Configurable HTTP Proxy's API, but does not require host-routing support).

**Comment by yuvipanda** [comment]
Ok, so only the host support is something that CHP has but jupyter doesn't use, right?

**Comment by yuvipanda** [comment]
Probably also need to add info about the Authorization header.

**Comment by yuvipanda** [comment]
Rebased, squashed them around - is generic enough now, I think.

**Comment by rgbkrk** [comment]
Awesome!

**Pull request merged**
